# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overridden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
#
# ===================================================================
#
# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================
#spring:
#  application:
#    name: Product
#  profiles:
#    # The commented value for `active` can be replaced with valid Spring profiles to load.
#    # Otherwise, it will be filled in by maven when building the JAR file
#    # Either way, it can be overridden by `--spring.profiles.active` value passed in the commandline or `-Dspring.profiles.active` set in `JAVA_OPTS`
#    active: #spring.profiles.active#
#  data:
#    jpa:
#      repositories:
#        bootstrap-mode: deferred
#  jpa:
#    open-in-view: false
#    hibernate:
#      ddl-auto: update
#      naming:
#        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
#        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
#
#server:
#  port: 8081


#spring.jpa.hibernate.ddl-auto=update
#spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/testing
#spring.datasource.username=root
#spring.datasource.password=Atanu@#123456
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
##spring.jpa.show-sql: true